# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8589ce1405fa695436fa3a08051093eb0bcf4bdb1e6f97437ef9b0522e10a061e6ecfa24aacaa226697f3af22994be906ec1d3204f353a7897b76d914911e4de

test:
  secret_key_base: d9f4992532f14a9cf885b1facd98254fa91e70de6c68bd5c857ac7f6f895c1e7ad2069f1e1431d5da5d194e1830b12b6a493248cb56c357f485d97e35e776fd9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
